### ISSUE TITLE
Question: any ideas on why tasks always fail at `failed to create Cloudwatch log stream`

### ISSUE THREAD

**Issue by zc62** [doctorray117/minecraft-ondemand#12]
Hi,

I'm pretty new to aws, and I followed your wonderful instructions, but unfortunately I had some issues I couldn't figure out why (and they are not in the troubleshooting section). I hope this is the right place to seek for help.

Basically the lambda works, the watchdog can trigger the lambda, and both tasks will try to run, but they will die immediately with the following error (they couldn't even print out any log, except just the error):
```
ResourceInitializationError: failed to validate logger args: create stream has been retried 1 times: failed to create Cloudwatch log stream: AccessDeniedException: User: arn:aws:sts::zzzzzzzzzzzz:assumed-role/ecs.task.minecraft-server/123456a999ee4b919...
```
Those two tasks are both running docker images, thus I have no idea why they have to create Cloudwatch logs. I can verify `ecs.task.minecraft-server` has all four policies added,

Any suggestions will be appreciated. Thank you.

EDIT: I forgot to mention, the desired task count is always 1, even after both tasks failed. Had to manually update it to 0.

**Comment by doctorray117** [comment]
Hey, thanks for trying this out.  That error could happen if the "assign public ip address" was set to DISABLED, as it wouldn't be able to reach the proper APIs to do all the stuff it needs to, and yeah that will get it stuck in a run loop because the secondary container wouldn't be able to set it to zero.  Please check and I'll add it to the troubleshooting section.  While it could be something else, this is the most likely.  Second most likely is that the VPC doesn't have an internet gateway attached., which is unlikely unless you either deleted it or created a new vpc without doing the other steps.

Go to your ECS console, click the service and then update.  on the second page, you'll see this:
![image](https://user-images.githubusercontent.com/18195344/133013710-0e374793-6d51-4cd1-9025-11b91d6c9b48.png)
Does it say ENABLED or DISABLED on the auto assign public ip?

If you need to change it, you probably need to delete the service and recreate it. I don't see a way to modify this value on an existing one.

Side note, I am tracking another issue (number 5) that only seems to show up on new AWS accounts, regarding security groups attached to EFS.  If you get it started but only the watchdog container launches, this might be the issue.  Hoping to wrap up the recommended procedure change for that in the next few hours after additional testing.

Good luck, please report back what you find.  Thanks.

**Comment by doctorray117** [comment]
Third possibility is that the security group that was created and attached to the service does not have the default outbound rule of all traffic / everywhere.  This is also unlikely as it would require deleting that default rule on the outbound tab on creation.  if this is it, it can be added back in the vpc or ec2 console under security groups...

**Comment by zc62** [comment]
I checked `Auto-assign public IP`, it was enabled. I also followed the security group change regarding issue 5, didn't help, exactly the same error message. (I kept those changes.)

One thing I notice is, when I first created the A Record for my subdomain (`minecraft.mydomain.xxx`), I put IP 1.1.1.1, however, even if I test the record or visit my own subdomain to trigger the server creation, the IP does not change. Is this an issue?

I also checked the outbound rules for the automatically created `minecraft-server` security group, it does have all traffic permission.

**Comment by doctorray117** [comment]
The issue appears to be that it can't communicate with the outside world. Evidence being specifically, it can't talk to the aws APIs or really do anything yet.

Is this a new AWS account and are you using the default VPC? If you created a new one for this, it requires an "internet gateway", "dhcp options", a "route table" with the internet gateway as the destination for 0.0.0.0/0, and I think that's it. You can check that these exist in the VPC console.

If this is an account that's been sitting dormant for a while, some of the above might not exist and would require creation. It's at least worth visiting those tabs and seeing.

**Comment by zc62** [comment]
Yes, a brand new account, the default VPC and it does seem to have all the things you mentioned.

**Comment by doctorray117** [comment]
Last thought before I go dig a bit more, when creating the task, did you let it create a default "task execution role"? This is separate from the task role itself.

This was not clear in earlier editions of the documentation but I added it a few days ago. I can post screenshots of its configuration shortly if you need it.

**Comment by zc62** [comment]
Oops, I did mess it up. Somehow I decided to choose `ecs.task.minecraft-server ` in the scroll down menu instead of staying at the default `create a new role` (maybe warn people not to do that?) The difficulty now is I couldn't find a way to delete old task definitions... I think I can figure it out, so closing the issue now. Thank you very much for helping!

**Comment by zc62** [comment]
Hooray! It worked! Though the old bad task definition stayed as revision 1 and I had to use revision 2 for the correct task. Any way to completely delete the old one?

**Comment by doctorray117** [comment]
Glad we found it.

You can revise the task definition, update the service, and if you want go back and retire the old version. Not necessary.

Please go also take a look at the updated step in the procedure directly under the efs creation, you'll need to add a rule to the default security group or else it won't be able to start the Minecraft server container.

Good luck!

**Comment by zc62** [comment]
> Please go also take a look at the updated step in the procedure directly under the efs creation, you'll need to add a rule to the default security group or else it won't be able to start the Minecraft server container.

Yes I did that.

Also I found aws says
> At this time, INACTIVE task definition revisions remain discoverable in your account indefinitely.
