### ISSUE TITLE
Task being terminated before Minecraft server even starts

### ISSUE THREAD

**Issue by Stealthii** [doctorray117/minecraft-ondemand#5]
Something is causing the watchdog process to terminate early, setting the task count to zero (maybe a SIGTERM, or something else. This seems to consistently happen 15-20 seconds after the watchdog container listens for connections.

I've set up the guide on two AWS accounts from scratch and encounter the same issue. Not sure if it's me or the guide, but something's missed.

| Timestamp | Message |
|----|----|
| 2021-09-09T12:31:08.332+01:00 | Waiting for Minecraft RCON to begin listening for connections
| 2021-09-09T12:31:24.423+01:00 | Setting desired task count to zero.

**Comment by doctorray117** [comment]
Fargate will send a sigterm to this container if it's unsuccessful at getting the other container started for whatever reason.  You could try removing the other container from the task definition temporarily to see if that's an issue.

One of the earlier issues I was debugging was that the other container couldn't mount the EFS volume properly.  If it didn't have the right permission or whatever.  So it's possible there's a lingering error in the EFS IAM policy.  Did you see my update to that policy? it was a couple of days ago.  Related to that, if the EFS was being mounted directly instead of the access point, then it wouldn't work unless the /minecraft folder was already created.  Using the Access Point, specifically with the create uid/gid/mode defined in the efs console, it will create the folders automatically and work.

I'll test your PR and merge/update within the next few hours.

**Comment by doctorray117** [comment]
Good morning,

I was able to do it from scratch successfully on a new account, however I ran across a few gotchas in the docs as well as have thought of a better workflow, to cluster all the IAM stuff together and things, and will be updating the procedure.

Were you able to get yours working?  I think the EFS ARN might be the issue you had specifically, as there's no clean place to copy it from, you need to derive it from the filesystem id.

Thanks

**Comment by doctorray117** [comment]
Hi, I'm going to close this for now as the docs have been clarified for the relevant policies, and I was able to go from start to finish on a different account.  Thank you for your help, PRs and feedback, and please let me know if you continue to have any issues from this.

**Comment by jidno** [comment]
I had the same issue and got it resolved by going to VPC -> Security groups -> Getting into the security group created in the ECS service -> Edit inbound rules -> Add NFS rule with port 2049 and with this security group as the source.

Then in EFS go to the created file system and in the network tab go to manage and add that security group to all availability zones. 

Hopefully this also resolves your issue.

**Comment by doctorray117** [comment]
That's interesting, I didn't think to go look at the default security group attached to the EFS, that could absolutely be a blocker on new/default VPCs.  I'll re-open and do a real start-to-finish on a new account and see if any modifications to the default security group that gets attached to EFS are necessary.

**Comment by doctorray117** [comment]
Okay, on an existing account, I went to a region I've never used before, and it had a default vpc, with a single default security group (allowing all from itself on inbound rules), and when I created an EFS drive, it assigned that default security group to it.  Therefore, any ECS task launched in the same VPC would have access to it with no additional modifications.
![image](https://user-images.githubusercontent.com/18195344/133001427-c41e8aad-1873-47a6-b35f-8065c15aae76.png)
![image](https://user-images.githubusercontent.com/18195344/133001477-fd0d07a2-420b-4e33-b1c2-26cfdb5deb21.png)
However, this was on an account that is several years old.  The behavior may be different on a new account created today.  So I guess I'll go make a new one and see what happens...

**Comment by doctorray117** [comment]
OK, I was able to confirm it not working out of the box on a freshly created AWS account in 100% us-east-1.  I'm flipping on Cloudtrail to try and catch the exact problem.  Even with the default vpc and the information above verified, it seems something is different.  Hoping to find the exact problem in cloudtrail logs.  fingers crossed.

**Comment by doctorray117** [comment]
Validated with an ec2 instance that a new account does not have network level access to efs by default, which makes sense because I didn't assign the default security group to my instance, just like the ecs service does not get assigned the default security group.  Easy workarounds obviously are modifying the default security group to accept all connections from within the CIDR but the design is such that it accepts everything from its concurrent members.  I would like to understand _why_ it does work with preexisting accounts before updating the documentation.  I will continue to work on this tonight.

**Comment by doctorray117** [comment]
This has been addressed.  Thank you both @Stealthii and @jidno for helping narrow it down.  My mistake was that I had previously added the VPC's CIDR to the default security group, and I suspect many others had as well.  I've added a [step](https://github.com/doctorray117/minecraft-ondemand#allow-access-to-efs-from-within-the-vpc) after EFS creation that adds the appropriate port to the default security group, with a suggestion that more advanced users create an additional security group for this purpose.  @jidno your workaround is fine, I think this mod is easier though.  Closing the issue.
